### ISSUE TITLE
Miner starts and terminates after a second

### ISSUE THREAD

**Issue by krispipeleers** [JohnnyFFM/miner-burst#1]
Was trying the new miner and it start good, displays below message in the DOS window and terminates. I'm using an older machine, so using the SSE build.

BURST miner, v1.170900_POC2 Programming: dcct (Linux) & Blago (Windows) POC2 mod: Quibus & Johnny (5/2018) CPU support: SSE SSE2 SSE3 SSE4.2 GenuineIntel Intel(R) Core(TM) i7 CPU 860 @ 2.80GHz [8 cores] RAM: 6144 Mb

**Comment by thothloki** [comment]
same issue as well

**Comment by JohnnyFFM** [comment]
Looking into this right now...

**Comment by krispipeleers** [comment]
Paul W on Twitter has the same problem. Let me know how I can help.

**Comment by JohnnyFFM** [comment]
I was able to replicate the issue and think I've found a fix. I'm going to release a new version now (901) and would require feedback if it fixes the issue. Cheers, Johnny

**Comment by krispipeleers** [comment]
Ok will test first thing in the morning! Thanks for the quick fix!

**Comment by DAProgs** [comment]
Had the issue with Xeon CPUs, the 901 patch works fine. Thanks

**Comment by thothloki** [comment]
901 works great. Thanks Johnny!

**Comment by krispipeleers** [comment]
Working for me as well! Thanks!
