### ISSUE TITLE
Miner frequently and randomly shutting down

### ISSUE THREAD

**Issue by ghost** [JohnnyFFM/miner-burst#10]
Im unsure as to why this is occuring, but multiple times a day the miner will completely shutdown. Not crash, but entirely quit. After restarting the program it works fine again, and restarting the machine does not help. Might still be a localized problem since I am running the miner on two machines and only have this issue on one.

OS - Windows 10
Using mixed PoC1 and PoC2 plots

**Comment by JohnnyFFM** [comment]
Could be an Antivirus app thread detection.

**Comment by JohnnyFFM** [comment]
is your ShowWinner set to true?

**Comment by ghost** [comment]
I have made sure all antivirus protection is off, but the issue presisted.

ShowWinner was true, retrying with it as false.

**Comment by ghost** [comment]
So its been about 24hrs now and the miner has been running continuously since changing ShowWinner to false.

Thanks!

**Comment by JohnnyFFM** [comment]
Excellent. The new beta version 997 has a fix for the showwinner. However, to make showwinner work, a non-ssl wallet needs to be used as info address (i.e best is a local wallet).

**Comment by ghost** [comment]
The issue happened with both the initial release as well as the 997 release. After my initial post I uninstalled and updated to 997 and still had the issue, but the showwinner change has appeard to fix it (now ~36hrs with no issue).

I am solo mining and running local wallets (Qbundle) on the problematic rig, so that shouldnt be the issue.

**Comment by JohnnyFFM** [comment]
Ok I might need to relook into 997 then. I made the showwinner function work in that version, but didnt check what happens if an ssl infoaddr is set instead of a non-ssl. This might cause the showwinner function to crash.
